import type { CatalogProduct } from "./../types/product";
import imagen3 from "../assets/imagen3.jpeg";
import imagen4 from "../assets/imagen4.jpeg";
import imagen5 from "../assets/imagen5.jpeg";
import imagen6 from "../assets/imagen6.jpeg";
import imagen7 from "../assets/imagen7.jpeg";
import imagen8 from "../assets/imagen8.jpeg";
import imagen9 from "../assets/imagen9.jpeg";
import imagen10 from "../assets/imagen10.jpeg";
import imagen12 from "../assets/imagen12.jpeg";
import type { ProductBase } from "../types/product";

export const mockProducts: CatalogProduct[] = [
  {
    id: 1,
    nombre: "Reloj Premium",
    descripcion: "Reloj de lujo con acabado premium y movimiento suizo",
    precio: 550.0,
    stock: 8,
    marca: "Luxury Time",
    imagenUrl: imagen3,
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-15T10:00:00",
    badge: "Nuevo",
    isFeatured: true,
  },
  {
    id: 2,
    nombre: "Dunk Low 'Pine Green'",
    descripcion:
      "Zapatillas deportivas de edición limitada con diseño colaborativo",
    precio: 540.0,
    stock: 12,
    marca: "Collaboration",
    imagenUrl: imagen4,
    activo: true,

    categoria: "Calzado",
    fechaCreacion: "2026-01-10T14:30:00",
    badge: "Destacado",
    isFeatured: true,
  },
  {
    id: 3,
    nombre: "Essentials Hoodie 'Moss'",
    descripcion: "Sudadera oversized de algodón premium con diseño minimalista",
    precio: 180.0,
    stock: 25,
    marca: "Essentials",
    imagenUrl: imagen5,
    activo: true,

    categoria: "Ropa",
    fechaCreacion: "2026-01-12T09:15:00",
    isFeatured: true,
  },
  {
    id: 4,
    nombre: "Logo Tee",
    descripcion: "Camiseta clásica de algodón con logo bordado",
    precio: 95.0,
    stock: 45,
    marca: "Classic",
    imagenUrl: imagen6,
    activo: true,

    categoria: "Ropa",
    fechaCreacion: "2026-01-08T11:20:00",
    isFeatured: false,
  },
  {
    id: 5,
    nombre: "Retro 1 'University Blue'",
    descripcion: "Zapatillas icónicas con diseño retro y colorway exclusivo",
    precio: 480.0,
    stock: 3,
    marca: "Iconic",
    imagenUrl: imagen7,
    activo: true,

    categoria: "Calzado",
    fechaCreacion: "2026-01-18T16:45:00",
    badge: "Últimas unidades",
    isFeatured: true,
  },
  {
    id: 6,
    nombre: "Air Max 270 'Red Fury'",
    descripcion: "Zapatillas de alto rendimiento con tecnología Air Max",
    precio: 210.0,
    stock: 18,
    marca: "Performance",
    imagenUrl: imagen8,
    activo: true,

    categoria: "Calzado",
    fechaCreacion: "2026-01-20T13:00:00",
    isFeatured: true,
  },
  {
    id: 7,
    nombre: "Premium Watch 'Gold Edition'",
    descripcion: "Reloj de lujo con acabado dorado y detalles exclusivos",
    precio: 1250.0,
    stock: 5,
    marca: "Luxury",
    imagenUrl: imagen9,
    activo: true,

    categoria: "Accesorios",
    fechaCreacion: "2026-01-22T10:30:00",
    badge: "Destacado",
    isFeatured: true,
  },
  {
    id: 8,
    nombre: "Urban Jacket 'Black'",
    descripcion: "Chaqueta urbana con diseño moderno y múltiples bolsillos",
    precio: 340.0,
    stock: 15,
    marca: "Street",
    imagenUrl: imagen10,
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-25T15:20:00",
    isFeatured: true,
  },
  {
    id: 9,
    nombre: "Urban Bomber 'Midnight'",
    descripcion: "Chamarra bomber con forro acolchado y cierre de cremallera",
    precio: 340.0,
    stock: 22,
    marca: "Street",
    imagenUrl: imagen12,
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-28T12:10:00",
    isFeatured: true,
  },
];

// Mock data - Reemplazar con datos reales de la API
export const mockProductsAdmin: ProductBase[] = [
  {
    id: 1,
    nombre: "Sudadera Oversized Obsidian",
    descripcion: "Sudadera premium de algodón oversize con diseño minimalista",
    precio: 420.0,
    stock: 12,
    marca: "Prime Drip",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDYKZNEpIrokFh01shr5dwF4SNmAoAn-gvUgw9_OlWG3VDJ5OGAEGsi7jyz5kI77SAz5GQRpPlwqwXWjkgaZ439yJlU-b5SmGDTK9ujA5Ow3cYlvmtdpydyH3TfM_FiNcoQxB-6O5xUQXk-vdXKepkN-8QqkInQ1MSZpMqhSXLrgc1Jg0nx619S6DG04kaRxzGNtsCigjOnqEj8SoLsPlKbDyNn50A55n1WWqXqkIvnq5Kw3fw41CQk9ZBlyCRCbpqytesch73B2TU2",
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-15T10:30:00",
  },
  {
    id: 2,
    nombre: "Cyber Runner Low-Top",
    descripcion:
      "Zapatillas deportivas de edición limitada con tecnología avanzada",
    precio: 890.0,
    stock: 3,
    marca: "Runner Co",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCyalmBK3Ob5txvjrLtqK83EftXZP35mmW1Rrb2KnoauQRXz54Gdq1qjq-eQM2ESeoFaez9XuIairA2oRszAKpb5EJSaDUQ9OIOBsqFNeW_17UvMCRXlvl7Y9VnuVrRItbkmC475F6Xt5Y0I-wETttyZ4IgdfONfQuZhsvqQVgCZwmV1z2YhVy3ei6PVPSUpTsxvh7EpdFmYkCFr_41TslVhDYhgzrEmFXMTWKtM5AQzg4mlnbzUYXpHsZT03ENBpxijyV1c-ep0tTE",
    activo: true,
    categoria: "Calzado",
    fechaCreacion: "2026-01-20T14:45:00",
  },
  {
    id: 3,
    nombre: "Camiseta Monolith Heavyweight",
    descripcion: "Camiseta de algodón pesado con corte regular",
    precio: 185.0,
    stock: 45,
    marca: "Monolith",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBgaEziuD3i3CYtxdy82RaLxkoNqsAFjhjL6jIEA5yAc8xF2yV2apYfAkIdls9DekN4IDke04gb0Qo2ylkEkAPuL1G5LJBincoMYn822JI8TGGKNb6SkbB9oURTftlLUixN0-YHAiJRxtF2Pa8tH9RRq6GzXGrQ3HVHlU5pZsFqFX91E1aK5GjSsPv190dIce2N-LmoqsN1F8EwWewjooKKxmy0wDc8_Z27wi3TwtSWcHeztFoHehiPfri034aTzaF-Ik_J16WVmUTg",
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-18T09:15:00",
  },
  {
    id: 4,
    nombre: "Pantalón Cargo Structural",
    descripcion: "Pantalón cargo con múltiples bolsillos y diseño funcional",
    precio: 350.0,
    stock: 0,
    marca: "Urban Wear",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBvPA7vAz5U1kgMXPmRjgu-udpFzkT5uQX4UUXCGc4pX_LAHsjsBfGDpiz4OWDMWyCM51lVMfrvAGMT0H6DptoC-H0DWIoo9ccT9dmLa2eX3hs4aZKrMGg_UUAqWbQ-qK3UL4HZoCoLoFzvumKblwz2k4s0F0FugGHYaSD1aOloHM78zg-NxRvILE-xGtGCg-oBiqDasjAoRFO9jt4wr97ICpjxQjMlPiXOP9Gyuz4WXuRIrAMD29CobZVBHXiZtNI_GNmncVngrSYZ",
    activo: false,
    categoria: "Ropa",
    fechaCreacion: "2025-12-10T16:20:00",
  },
  {
    id: 5,
    nombre: "Reloj Premium Gold",
    descripcion: "Reloj de lujo con acabado dorado y movimiento suizo",
    precio: 1250.0,
    stock: 8,
    marca: "Luxury Time",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDYKZNEpIrokFh01shr5dwF4SNmAoAn-gvUgw9_OlWG3VDJ5OGAEGsi7jyz5kI77SAz5GQRpPlwqwXWjkgaZ439yJlU-b5SmGDTK9ujA5Ow3cYlvmtdpydyH3TfM_FiNcoQxB-6O5xUQXk-vdXKepkN-8QqkInQ1MSZpMqhSXLrgc1Jg0nx619S6DG04kaRxzGNtsCigjOnqEj8SoLsPlKbDyNn50A55n1WWqXqkIvnq5Kw3fw41CQk9ZBlyCRCbpqytesch73B2TU2",
    activo: true,
    categoria: "accesorios",
    fechaCreacion: "2026-01-25T11:00:00",
  },
  {
    id: 6,
    nombre: "Chaqueta Bomber Eclipse",
    descripcion: "Chaqueta bomber con forro acolchado y cierre de cremallera",
    precio: 580.0,
    stock: 15,
    marca: "Eclipse Wear",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBgaEziuD3i3CYtxdy82RaLxkoNqsAFjhjL6jIEA5yAc8xF2yV2apYfAkIdls9DekN4IDke04gb0Qo2ylkEkAPuL1G5LJBincoMYn822JI8TGGKNb6SkbB9oURTftlLUixN0-YHAiJRxtF2Pa8tH9RRq6GzXGrQ3HVHlU5pZsFqFX91E1aK5GjSsPv190dIce2N-LmoqsN1F8EwWewjooKKxmy0wDc8_Z27wi3TwtSWcHeztFoHehiPfri034aTzaF-Ik_J16WVmUTg",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-12T08:00:00",
  },
  {
    id: 7,
    nombre: "Gorra Streetwear Premium",
    descripcion: "Gorra ajustable con bordado 3D y visera curva",
    precio: 95.0,
    stock: 67,
    marca: "Street Co",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCyalmBK3Ob5txvjrLtqK83EftXZP35mmW1Rrb2KnoauQRXz54Gdq1qjq-eQM2ESeoFaez9XuIairA2oRszAKpb5EJSaDUQ9OIOBsqFNeW_17UvMCRXlvl7Y9VnuVrRItbkmC475F6Xt5Y0I-wETttyZ4IgdfONfQuZhsvqQVgCZwmV1z2YhVy3ei6PVPSUpTsxvh7EpdFmYkCFr_41TslVhDYhgzrEmFXMTWKtM5AQzg4mlnbzUYXpHsZT03ENBpxijyV1c-ep0tTE",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-28T15:30:00",
  },
  {
    id: 8,
    nombre: "Botas Combat Urban",
    descripcion: "Botas militares de cuero con suela antideslizante",
    precio: 675.0,
    stock: 2,
    marca: "Combat Pro",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBvPA7vAz5U1kgMXPmRjgu-udpFzkT5uQX4UUXCGc4pX_LAHsjsBfGDpiz4OWDMWyCM51lVMfrvAGMT0H6DptoC-H0DWIoo9ccT9dmLa2eX3hs4aZKrMGg_UUAqWbQ-qK3UL4HZoCoLoFzvumKblwz2k4s0F0FugGHYaSD1aOloHM78zg-NxRvILE-xGtGCg-oBiqDasjAoRFO9jt4wr97ICpjxQjMlPiXOP9Gyuz4WXuRIrAMD29CobZVBHXiZtNI_GNmncVngrSYZ",
    activo: true,
    categoria: "Calzado",
    fechaCreacion: "2026-01-10T12:45:00",
  },
  {
    id: 9,
    nombre: "Mochila Tech Pro",
    descripcion: "Mochila técnica con compartimento para laptop y carga USB",
    precio: 245.0,
    stock: 28,
    marca: "Tech Gear",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDYKZNEpIrokFh01shr5dwF4SNmAoAn-gvUgw9_OlWG3VDJ5OGAEGsi7jyz5kI77SAz5GQRpPlwqwXWjkgaZ439yJlU-b5SmGDTK9ujA5Ow3cYlvmtdpydyH3TfM_FiNcoQxB-6O5xUQXk-vdXKepkN-8QqkInQ1MSZpMqhSXLrgc1Jg0nx619S6DG04kaRxzGNtsCigjOnqEj8SoLsPlKbDyNn50A55n1WWqXqkIvnq5Kw3fw41CQk9ZBlyCRCbpqytesch73B2TU2",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-22T09:20:00",
  },
  {
    id: 10,
    nombre: "Cinturón Leather Premium",
    descripcion: "Cinturón de cuero genuino con hebilla metálica",
    precio: 125.0,
    stock: 0,
    marca: "Leather Co",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBgaEziuD3i3CYtxdy82RaLxkoNqsAFjhjL6jIEA5yAc8xF2yV2apYfAkIdls9DekN4IDke04gb0Qo2ylkEkAPuL1G5LJBincoMYn822JI8TGGKNb6SkbB9oURTftlLUixN0-YHAiJRxtF2Pa8tH9RRq6GzXGrQ3HVHlU5pZsFqFX91E1aK5GjSsPv190dIce2N-LmoqsN1F8EwWewjooKKxmy0wDc8_Z27wi3TwtSWcHeztFoHehiPfri034aTzaF-Ik_J16WVmUTg",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-05T14:10:00",
  },
  {
    id: 11,
    nombre: "Shorts Deportivos Sprint",
    descripcion: "Shorts de alto rendimiento con tecnología Dri-Fit",
    precio: 155.0,
    stock: 42,
    marca: "Sprint Pro",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCyalmBK3Ob5txvjrLtqK83EftXZP35mmW1Rrb2KnoauQRXz54Gdq1qjq-eQM2ESeoFaez9XuIairA2oRszAKpb5EJSaDUQ9OIOBsqFNeW_17UvMCRXlvl7Y9VnuVrRItbkmC475F6Xt5Y0I-wETttyZ4IgdfONfQuZhsvqQVgCZwmV1z2YhVy3ei6PVPSUpTsxvh7EpdFmYkCFr_41TslVhDYhgzrEmFXMTWKtM5AQzg4mlnbzUYXpHsZT03ENBpxijyV1c-ep0tTE",
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-17T11:25:00",
  },
  {
    id: 12,
    nombre: "Gafas de Sol Aviator",
    descripcion: "Gafas estilo aviador con lentes polarizadas UV400",
    precio: 320.0,
    stock: 19,
    marca: "Vision Pro",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBvPA7vAz5U1kgMXPmRjgu-udpFzkT5uQX4UUXCGc4pX_LAHsjsBfGDpiz4OWDMWyCM51lVMfrvAGMT0H6DptoC-H0DWIoo9ccT9dmLa2eX3hs4aZKrMGg_UUAqWbQ-qK3UL4HZoCoLoFzvumKblwz2k4s0F0FugGHYaSD1aOloHM78zg-NxRvILE-xGtGCg-oBiqDasjAoRFO9jt4wr97ICpjxQjMlPiXOP9Gyuz4WXuRIrAMD29CobZVBHXiZtNI_GNmncVngrSYZ",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-14T16:40:00",
  },
  {
    id: 13,
    nombre: "Polo Classic Fit",
    descripcion: "Polo de algodón piqué con corte clásico",
    precio: 175.0,
    stock: 5,
    marca: "Classic Wear",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDYKZNEpIrokFh01shr5dwF4SNmAoAn-gvUgw9_OlWG3VDJ5OGAEGsi7jyz5kI77SAz5GQRpPlwqwXWjkgaZ439yJlU-b5SmGDTK9ujA5Ow3cYlvmtdpydyH3TfM_FiNcoQxB-6O5xUQXk-vdXKepkN-8QqkInQ1MSZpMqhSXLrgc1Jg0nx619S6DG04kaRxzGNtsCigjOnqEj8SoLsPlKbDyNn50A55n1WWqXqkIvnq5Kw3fw41CQk9ZBlyCRCbpqytesch73B2TU2",
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-19T13:55:00",
  },
  {
    id: 14,
    nombre: "Calcetines Tech Athletic",
    descripcion: "Pack de 3 pares con compresión y tecnología anti-olor",
    precio: 65.0,
    stock: 156,
    marca: "Athletic Pro",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBgaEziuD3i3CYtxdy82RaLxkoNqsAFjhjL6jIEA5yAc8xF2yV2apYfAkIdls9DekN4IDke04gb0Qo2ylkEkAPuL1G5LJBincoMYn822JI8TGGKNb6SkbB9oURTftlLUixN0-YHAiJRxtF2Pa8tH9RRq6GzXGrQ3HVHlU5pZsFqFX91E1aK5GjSsPv190dIce2N-LmoqsN1F8EwWewjooKKxmy0wDc8_Z27wi3TwtSWcHeztFoHehiPfri034aTzaF-Ik_J16WVmUTg",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-26T10:15:00",
  },
  {
    id: 15,
    nombre: "Sudadera Tech Hoodie",
    descripcion: "Hoodie con bolsillos ocultos y tecnología thermoreguladora",
    precio: 495.0,
    stock: 0,
    marca: "Tech Urban",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCyalmBK3Ob5txvjrLtqK83EftXZP35mmW1Rrb2KnoauQRXz54Gdq1qjq-eQM2ESeoFaez9XuIairA2oRszAKpb5EJSaDUQ9OIOBsqFNeW_17UvMCRXlvl7Y9VnuVrRItbkmC475F6Xt5Y0I-wETttyZ4IgdfONfQuZhsvqQVgCZwmV1z2YhVy3ei6PVPSUpTsxvh7EpdFmYkCFr_41TslVhDYhgzrEmFXMTWKtM5AQzg4mlnbzUYXpHsZT03ENBpxijyV1c-ep0tTE",
    activo: false,
    categoria: "Ropa",
    fechaCreacion: "2025-12-20T17:00:00",
  },
  {
    id: 16,
    nombre: "Riñonera Crossbody",
    descripcion: "Bolso tipo riñonera convertible en crossbody",
    precio: 189.0,
    stock: 33,
    marca: "Urban Bag",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBvPA7vAz5U1kgMXPmRjgu-udpFzkT5uQX4UUXCGc4pX_LAHsjsBfGDpiz4OWDMWyCM51lVMfrvAGMT0H6DptoC-H0DWIoo9ccT9dmLa2eX3hs4aZKrMGg_UUAqWbQ-qK3UL4HZoCoLoFzvumKblwz2k4s0F0FugGHYaSD1aOloHM78zg-NxRvILE-xGtGCg-oBiqDasjAoRFO9jt4wr97ICpjxQjMlPiXOP9Gyuz4WXuRIrAMD29CobZVBHXiZtNI_GNmncVngrSYZ",
    activo: true,
    categoria: "Accesorios",
    fechaCreacion: "2026-01-23T14:30:00",
  },
  {
    id: 17,
    nombre: "Chamarra Denim Vintage",
    descripcion: "Chamarra de mezclilla con lavado vintage y rotos",
    precio: 525.0,
    stock: 9,
    marca: "Vintage Co",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDYKZNEpIrokFh01shr5dwF4SNmAoAn-gvUgw9_OlWG3VDJ5OGAEGsi7jyz5kI77SAz5GQRpPlwqwXWjkgaZ439yJlU-b5SmGDTK9ujA5Ow3cYlvmtdpydyH3TfM_FiNcoQxB-6O5xUQXk-vdXKepkN-8QqkInQ1MSZpMqhSXLrgc1Jg0nx619S6DG04kaRxzGNtsCigjOnqEj8SoLsPlKbDyNn50A55n1WWqXqkIvnq5Kw3fw41CQk9ZBlyCRCbpqytesch73B2TU2",
    activo: true,
    categoria: "Ropa",
    fechaCreacion: "2026-01-11T09:45:00",
  },
  {
    id: 18,
    nombre: "Pulsera Leather Braided",
    descripcion: "Pulsera de cuero trenzado con cierre magnético",
    precio: 85.0,
    stock: 73,
    marca: "Leather Art",
    imagenUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBgaEziuD3i3CYtxdy82RaLxkoNqsAFjhjL6jIEA5yAc8xF2yV2apYfAkIdls9DekN4IDke04gb0Qo2ylkEkAPuL1G5LJBincoMYn822JI8TGGKNb6SkbB9oURTftlLUixN0-YHAiJRxtF2Pa8tH9RRq6GzXGrQ3HVHlU5pZsFqFX91E1aK5GjSsPv190dIce2N-LmoqsN1F8EwWewjooKKxmy0wDc8_Z27wi3TwtSWcHeztFoHehiPfri034aTzaF-Ik_J16WVmUTg",
    activo: true,
    categoria: "Joyería",
    fechaCreacion: "2026-01-27T12:00:00",
  },
];
